### PR TITLE
Trait compatibility fix

### LINKED ISSUE #164: TaggableContract not compatible with TaggableTrait
Some function signatures from TaggableContract like https://github.com/rtconner/laravel-tagging/blob/laravel-5/src/Contracts/TaggableContract.php#L59 are not compatible with the TaggableTrait https://github.com/rtconner/laravel-tagging/blob/laravel-5/src/Taggable.php#L181

### PR DESCRIPTION
**Pull request by Firtzberg**
Fixes #164

### CODE REVIEW

File: src/Taggable.php [hunk 1]
```diff
@@ -331,7 +331,7 @@ private function removeTag($tagName)
     /**
      * Return an array of all of the tags that are in use by this model
      *
-     * @return Collection|Tagged[]
```
Comment (rtconner) [inline src/Taggable.php]: This change was incorrect. `Collection|Tagged[]` is correct
